# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.2
    environment:
      APP_ENV: testing
    working_directory: ~/laraBookKeeping
    steps:
      - checkout
      - run:
          name: Install Node.js and CSpell(spell checker)
          command: |
            sudo apt update
            sudo apt install -y nodejs npm
            sudo npm install -g n
            sudo n stable
            sudo npm install -g cspell
      - run:
          name: Install xdebug
          command: |
            sudo pecl install xdebug
            sudo docker-php-ext-enable xdebug
      - run:
          name: Install Composer 2.x
          command: |
            sudo curl -sS -o /usr/local/bin/composer https://getcomposer.org/composer-2.phar
            sudo chmod a+x /usr/local/bin/composer
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "book-keeping/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          command: composer install -n --prefer-dist
          working_directory: ~/laraBookKeeping/book-keeping
      - save_cache:
          key: v1-dependencies-{{ checksum "book-keeping/composer.json" }}
          paths:
            - ./book-keeping/vendor
      - run:
          command: cp .env.testing.example .env.testing && php artisan key:generate --env=testing
          working_directory: ~/laraBookKeeping/book-keeping
      - run: mkdir -p build/logs
      - run:
          command: cspell "**/*.php"
          working_directory: ~/laraBookKeeping
      # Install Node packages and build assets and run tests with phpunit
      - run:
          command: npm ci
          working_directory: ~/laraBookKeeping/book-keeping
      - run:
          command: npm run build
          working_directory: ~/laraBookKeeping/book-keeping
      - run:
          command: npx prettier --check **/*.blade.php
          working_directory: ~/laraBookKeeping/book-keeping
      # run tests with phpunit
      - run:
          command: XDEBUG_MODE=coverage vendor/bin/phpunit -d memory_limit=512M --coverage-clover ../build/logs/clover.xml
          working_directory: ~/laraBookKeeping/book-keeping
      - run: php book-keeping/vendor/bin/php-coveralls -vvv
