name: Static Analysis by PHPStan

on: [push]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        working_dir: book-keeping
    - name: run Larastan
      run: XDEBUG_MODE=off vendor/bin/phpstan analyse
      working-directory: ./book-keeping
